# Generated by Django 5.1.3 on 2024-12-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0002_alter_category_description_alter_product_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="product/image",
                verbose_name="Изображение",
            ),
        ),
    ]
