# Generated by Django 5.1.3 on 2025-02-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="check_box",
            field=models.BooleanField(default=False, verbose_name="Чекбокс"),
        ),
    ]
