# Generated by Django 5.1.3 on 2025-02-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_options_product_is_published_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="check_box",
        ),
    ]
