# Generated by Django 5.1.3 on 2025-02-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_remove_product_check_box"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["product_name"],
                "permissions": [
                    ("can_unpublish_product", "Can unpublish product"),
                    ("can_delete_product", "Can delete product"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
